### ISSUE TITLE
Capitalized foreign letters cause unhandled exception at UnidentifiedTokenParser

### ISSUE THREAD

**Issue by faraday** [ahmetaa/zemberek-nlp#19]
When TurkishSentenceParser encounters an unidentified letter, the exception below is thrown:

Sample input:
`TOMÙ`

```
java.lang.IllegalStateException: Letter sequence is empty
    at zemberek.core.turkish.TurkicSeq.lastLetter(TurkicSeq.java:103)
    at zemberek.morphology.lexicon.tr.StemNodeGenerator.calculateAttributes(StemNodeGenerator.java:95)
    at zemberek.morphology.lexicon.tr.StemNodeGenerator.calculateAttributes(StemNodeGenerator.java:79)
    at zemberek.morphology.lexicon.tr.StemNodeGenerator.generate(StemNodeGenerator.java:57)
    at zemberek.morphology.lexicon.graph.DynamicLexiconGraph.addDictionaryItem(DynamicLexiconGraph.java:55)
    at zemberek.morphology.apps.UnidentifiedTokenParser.parse(UnidentifiedTokenParser.java:61)
    at zemberek.morphology.apps.TurkishSentenceParser.parse(TurkishSentenceParser.java:73)
    at morphology.DisambiguateSentences.parseAndDisambiguate(DisambiguateSentences.java:21)
```

This is abnormal since TurkishSentenceParser doesn't expect this exception from UnidentifiedTokenParser.

**Comment by ahmetaa** [comment]
Analyzer does not throw an exception for this word now. But it does not offer a solution. Closing anyway.
