### ISSUE TITLE
weblogin deploy sorunu

### ISSUE THREAD

**Issue by musaay** [ahmetaa/zemberek-nlp#204]
dependency i projeye ekleyip weblogic e deploy ettiğimizde aşağıdaki hata alınıyor. İlgili paketide nette bulamadım. https://stackoverflow.com/questions/50717324/java-lang-classnotfoundexception-afu-com-sun-source-tree-treekind?noredirect=1&lq=1 buradaki cevaplardan ilerlemeyi denedim fakat işe yaramadı. Bir fikriniz olur mu hata ile ilgili

Caused By: java.lang.ClassNotFoundException: afu.com.sun.source.tree.Tree$Kind
                at weblogic.utils.classloaders.GenericClassLoader.findLocalClass(GenericClassLoader.java:1029)
                at weblogic.utils.classloaders.GenericClassLoader.findClass(GenericClassLoader.java:990)
                at weblogic.utils.classloaders.ChangeAwareClassLoader.findClass(ChangeAwareClassLoader.java:104)
                at weblogic.utils.classloaders.GenericClassLoader.doFindClass(GenericClassLoader.java:611)
                at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:543)
                at weblogic.utils.classloaders.GenericClassLoader.loadClass(GenericClassLoader.java:496)
                at weblogic.utils.classloaders.ChangeAwareClassLoader.loadClass(ChangeAwareClassLoader.java:72)
                at weblogic.utils.classloaders.ChangeAwareClassLoader.loadClass(ChangeAwareClassLoader.java:53)
                at java.lang.Class.getDeclaredMethods0(Native Method)
                at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
                at java.lang.Class.getDeclaredMethods(Class.java:1975)
                at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:112)
                at sun.reflect.annotation.AnnotationType$1.run(AnnotationType.java:109)
                at java.security.AccessController.doPrivileged(Native Method)
                at sun.reflect.annotation.AnnotationType.<init>(AnnotationType.java:109)
                at sun.reflect.annotation.AnnotationType.getInstance(AnnotationType.java:85)
                at sun.reflect.annotation.AnnotationParser.parseAnnotation2(AnnotationParser.java:266)
                at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:120)
                at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:72)
                at java.lang.Class.createAnnotationData(Class.java:3521)
                at java.lang.Class.annotationData(Class.java:3510)
                at java.lang.Class.getAnnotations(Class.java:3446)
                at weblogic.application.utils.annotation.AnnotationAncestry.isExtendedAnnotationDeep(AnnotationAncestry.java:107)

**Comment by ahmetaa** [comment]
Burada proje içerisindeki ya da bağlı olan kütüphanelere ait bir hata yer almıyor. Başka hata logu var mı?

Hangi zemberek sürümünü kullanıyorsunuz?

**Comment by musaay** [comment]
Selamlar

0.16.0 sürümünü kullanıyorum. Sorunu checker jarı ekleyerek düzelttim. Fakat sonrasında da aşağıdaki jar lar da problem oldu. Onları da ekledim. Projede acaba provided mı tanımladınız. Sanırım sorun ondan kaynaklanıyor. Yoksa eklemek gerekiyor. 

Not : Bu arada tomcat de sadece zemberek jar ı ekleyince hata almadan çalışıyor

            <dependency>
		    <groupId>org.antlr</groupId>
		    <artifactId>antlr4-runtime</artifactId>
		    <version>4.7</version>
		</dependency>
		
		<dependency>
			<groupId>com.github.ben-manes.caffeine</groupId>
			<artifactId>caffeine</artifactId>
			<version>2.6.2</version>
		</dependency>
		
		<dependency>
		    <groupId>org.checkerframework</groupId>
		    <artifactId>checker-qual</artifactId>
		    <version>2.5.8</version>
		</dependency>

		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>guava</artifactId>
			<version>27.0.1-jre</version>
		</dependency>
		
		<dependency>
			<groupId>com.google.guava</groupId>
			<artifactId>failureaccess</artifactId>
			<version>1.0.1</version>
		</dependency>
			
		<dependency>
		    <groupId>com.google.protobuf</groupId>
		    <artifactId>protobuf-java</artifactId>
		    <version>3.3.1</version>
		</dependency>
